# Generated by Django 5.1.3 on 2024-11-18 06:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_tasks_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(max_length=500)),
                ('task_state', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='tasks',
            name='assigned',
            field=models.ManyToManyField(related_name='contacts', to='backend_app.contacts'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='await_feedback',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasks',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='description',
            field=models.TextField(default='tex', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasks',
            name='duedate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasks',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('low', 'Low'), ('medium', 'Medium')], default='low', max_length=6),
        ),
        migrations.AddField(
            model_name='tasks',
            name='title',
            field=models.CharField(default='title', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasks',
            name='category',
            field=models.CharField(default='Technical Task', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='subtasks',
            field=models.ManyToManyField(related_name='subtasks', to='backend_app.subtask'),
        ),
    ]
