# Generated by Django 5.1.3 on 2024-11-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0003_subtask_tasks_assigned_tasks_await_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='circle_color',
            field=models.CharField(default='user-color-one', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='email',
            field=models.EmailField(default='first@first.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='initials',
            field=models.CharField(default='KM', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='lastname',
            field=models.CharField(default='müller', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='name',
            field=models.CharField(default='Kevin', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='phone',
            field=models.DecimalField(decimal_places=0, default=4915153962240, max_digits=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.CharField(choices=[('medium', 'Medium'), ('high', 'High'), ('low', 'Low')], default='low', max_length=6),
        ),
    ]
