# Generated by Django 5.1.3 on 2024-11-18 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0006_alter_tasks_priority_alter_tasks_subtasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='subtasks',
        ),
        migrations.AddField(
            model_name='subtask',
            name='task_description',
            field=models.TextField(default='this is a subtask description', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='backend_app.tasks'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='assigned',
            field=models.ManyToManyField(related_name='assigned', to='backend_app.contacts'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('high', 'High'), ('medium', 'Medium')], default='low', max_length=6),
        ),
    ]
