# Generated by Django 5.1.3 on 2024-11-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0007_remove_tasks_subtasks_subtask_task_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.CharField(choices=[('medium', 'Medium'), ('high', 'High'), ('low', 'Low')], default='low', max_length=6),
        ),
    ]
