# Generated by Django 5.1.3 on 2024-11-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0011_contacts_user_alter_tasks_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.CharField(choices=[('medium', 'Medium'), ('low', 'Low'), ('urgent', 'Urgent')], default='low', max_length=6),
        ),
    ]
